config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :price_per_night, :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_resto, only: %i[edit show update destroy]
  def index
    @flats = Flat.all
  end

  def show; end

  def new
    # hier moet wel iets staan om de form_for te kunnen gebruiken
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(params_flats)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit; end

  def update
    @flat.update(params_flats)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def find_flas
    @flat = Flat.find(params[:id])
  end

  def params_flats
    params.require(:flat).permit(:name, :address, :category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<header class="d-flex align-items-end">
  <div class='d-inline-flex p-2'>
        <h4>Simple AirBnB</h4>
  </div>
  <div class='ml-auto d-inline-flex p-2' >
      <input type="text" value="search for" class='text-align-right'>
      <button type="submit" class='btn btn-outline-primary p-1'>Search</button>
  </div>
  <div class='d-inline-flex p-2' >
        <%= link_to new_flat_path do %>
        <button type="button" class='btn btn-outline-primary p-1'>add flat</button>
        <% end %>
  </div>
</header>
<div class="container">
  <div class="row">
    <div class="col">
      <h1>All our Flats (<%=@flats.size %>)</h1>
        <div class='d-flex'>
        <% @flats.each do |flat| %>
          <div class="card">
            <div>
              <h4><%= link_to flat.name, flat_path(flat)%><h4>
              <p><i class="fas fa-users"> <%= flat.number_of_guests%></i></p>
              <p><i class="fas fa-euro-sign"> <%= flat.price_per_night%></i></p>
            </div>
            <div>
              <%= link_to%>
            </div>
          </div>
        <% end %>
        </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>